mass: 0.617 # [kg] # falcon7
tbm_fr: [0.075, -0.075, 0.0] # [m]
tbm_bl: [-0.075, 0.075, 0.0] # [m]
tbm_br: [-0.075, -0.075, 0.0] # [m]
tbm_fl: [0.075, 0.075, 0.0] # [m]
inertia: [[0.00164, 0, 0], [0, 0.00184, 0], [0, 0, 0.0030]] # [kgm^2] - rigid body inertia matrix in Gazebo
motor_omega_min: 150.0 # [rad/s]
motor_omega_max: 2800.0 # [rad/s]
motor_tau: 0.033 # [s]
motor_inertia_z: 9.3575e-6 # [kgm^2]
omega_max: [10.0, 10.0, 4.0] # [rad/s]
thrust_map: [1.562522e-6, 0.0, 0.0]
kappa: 0.022 # [Nm/N]
thrust_min: 0.0 # [N]
thrust_max: 8.5 # [N] per motor
rotors_config: "cross"
aero_coeff_1: [0.0, 0.0, 0.0] # [0.26, 0.28, 0.42] # [N/(v/m)]
aero_coeff_3: [0.0, 0.0, 0.0] # [N/(v/m)]
aero_coeff_h: 0.0 # 0.01 [N/(v^2/m^2)]
kd: [[0, 0, 0], [0, 0, 0], [0, 0, 0]] # simplesim values
