gridmap:
  frequency: 1        # which frequency do we want to send an updated map?
  map_id: "map"      # map name
  size_x: 12           # size of x in meters
  size_y: 12           # size of y in meters
  resolution: 0.01    # size of each grid
  map_origin_x: 0     # center x position of the map
  map_origin_y: 0     # center y position of the map
  publish_topic: "/occupancy_grid" # The topic name of the map publisher 

obstacles:
  inflate: True
  inflation_thickness: 0.2 # radius around obstacles to inflate
  create_static:
    use: true
    circles:
      x_center: []
      y_center: []
      radius: []
      names: []
    squares:
      x_center: [0, -3.3, -2.7, -1.5, -0.9, 0.3, -0.9, 0.3, 0.9, 2.1, 2.7]
      y_center: [0, -2.1, -0.9, -0.3, 0.9, 1.5, -2.7, -2.1, -0.9, -0.3, 0.9]
      length: [10, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]
      width: [8.5, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8]
      orientation_deg: [0, 0, 90, 0, 90, 0, 90, 0, 90, 0, 90] # 0 orientation means length is in x-direction
      line_thickness: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      names: ["bounds", "rectangle3x1_0", "rectangle3x1_1", "rectangle3x1_2", "rectangle3x1_3", "rectangle3x1_4", "rectangle3x1_5", "rectangle3x1_6", "rectangle3x1_7", "rectangle3x1_8", "rectangle3x1_9"]
  receiving_position:
    use: true
    circles:
      topics: []
      radius: []
    rectangles:
      topics: [/obstacles/rectangle2x1_0, /obstacles/rectangle2x1_1]
      lengths: [1.2, 1.2]
      widths: [0.6, 0.6]
      line_thickness: [0.01, 0.01, 0.01]
    lines:
      topics: []
      lengths: []
      line_thickness: []
  receiving_position_gazebo:
    use: false
    topic: "/gazebo/model_states"
    radius: 0.5

recording:
  static_circle_indices_to_record: []
  static_square_indices_to_record: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

visualization:
  static_circle_indices_to_visualize: []
  static_square_indices_to_visualize: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  marker_color: [0.7, 0.7, 0.7, 1]
  marker_z: 1.8
